// <auto-generated />
using System;
using MedShare.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedShare.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104221647_AddInicialTables")]
    partial class AddInicialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MedShare.Models.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoReceita")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DoadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDoacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeDoacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ValidadeDoacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoadorId");

                    b.HasIndex("InstituicaoId");

                    b.ToTable("Doacoes");
                });

            modelBuilder.Entity("MedShare.Models.Doador", b =>
                {
                    b.Property<int>("DoadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoadorCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoadorSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DoadorId");

                    b.ToTable("Doadores");
                });

            modelBuilder.Entity("MedShare.Models.Instituicao", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstituicaoCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoEndereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("MedShare.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MedShare.Models.Doacao", b =>
                {
                    b.HasOne("MedShare.Models.Doador", "Doador")
                        .WithMany()
                        .HasForeignKey("DoadorId");

                    b.HasOne("MedShare.Models.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doador");

                    b.Navigation("Instituicao");
                });
#pragma warning restore 612, 618
        }
    }
}
